function tbt=makeTbtForPelletPresented(alignmentDir, alignment)

if ~isfield(alignment,'isGrooming')
    alignment.isGrooming=zeros(size(alignment.cue));
end

settings=plotCueTriggered_settings();
settings.isOrchestra=1;
settings.plotfields={'pelletLoaded', ...
                     'cueZone_onVoff',...
                     'pelletLoaded',...
                     'movie_distractor',...
                     'optoOn',...
                     'interlockSamples',...
                     'reachStarts',...
                     'reach_ongoing',...
                     'success_reachStarts',...
                     'drop_reachStarts',...
                     'miss_reachStarts',...
                     'pelletmissingreach_reachStarts',...
                     'eating'};
settings.plotevents={'optoZone',...
                     'isGrooming',...
                     'success_reachStarts_pawOnWheel',...
                     'drop_reachStarts_pawOnWheel',...
                     'miss_reachStarts_pawOnWheel',...
                     'pelletmissingreach_reachStarts',...
                     'movie_distractor',...
                     'success_reachStarts',...
                     'drop_reachStarts',...
                     'miss_reachStarts',...
                     'cueZone_onVoff',...
                     'pelletPresented'};
settings.histoplotfields={'pelletPresented',...
                          'movie_distractor',...
                          'reachStarts'};
settings.trialType_plotfields={'pelletPresented',...
                          'movie_distractor',...
                          'success_reachStarts',...
                          'drop_reachStarts',...
                          'miss_reachStarts',...
                          'reachStarts',...
                          'goodReaches'};

tbt=plotCueTriggeredBehavior(alignment,'pelletPresented',0,settings);
save([alignmentDir '/tbt_pelletPresented.mat'],'tbt');
save([alignmentDir '/plotSettings_pelletPresented.mat'],'settings');